[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_N8N_WEBHOOK_URL = "https://anranzhou.app.n8n.cloud/webhook/ai-chat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200