[build]
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 环境变量配置示例
# [build.environment]
#   DEEPSEEK_API_KEY = "your_deepseek_api_key"
#   SUPABASE_URL = "your_supabase_url"
#   SUPABASE_ANON_KEY = "your_supabase_anon_key"